import { redirect } from 'next/navigation';
import { db } from '@/lib/db';
import { getSession } from '@/lib/auth';
export const dynamic = 'force-dynamic';
export default async function Dashboard() {
  if (!(await getSession())) redirect('/login');
  const stats = db.prepare(`SELECT (SELECT COUNT(*) FROM apps WHERE deleted_at IS NULL) apps,(SELECT COUNT(*) FROM ideas WHERE deleted_at IS NULL) ideas,(SELECT COUNT(*) FROM ideas WHERE deleted_at IS NULL AND status='published') published,(SELECT COALESCE(SUM(revenue),0) FROM performance_metrics) revenue`).get() as Record<string,any>;
  const apps = db.prepare(`SELECT apps.name,COUNT(ideas.id) ideas,SUM(CASE WHEN ideas.status='published' THEN 1 ELSE 0 END) published FROM apps LEFT JOIN ideas ON ideas.app_id=apps.id AND ideas.deleted_at IS NULL WHERE apps.deleted_at IS NULL GROUP BY apps.id ORDER BY ideas DESC`).all() as Record<string,any>[];
  const teams = db.prepare(`SELECT COALESCE(team,'Unassigned') team,COUNT(*) ideas,SUM(CASE WHEN status='approved' THEN 1 ELSE 0 END) approved,SUM(CASE WHEN deadline<date('now') AND status NOT IN ('published','archived','rejected') THEN 1 ELSE 0 END) overdue FROM ideas WHERE deleted_at IS NULL GROUP BY team ORDER BY ideas DESC`).all() as Record<string,any>[];
  const recent = db.prepare('select ideas.*,apps.name app_name from ideas join apps on apps.id=ideas.app_id where ideas.deleted_at is null order by ideas.updated_at desc limit 8').all() as Record<string,any>[];
  return <div className="space-y-6"><h1 className="text-3xl font-bold">Dashboard</h1><div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{Object.entries(stats).map(([key,value])=><div className="card" key={key}>{key}<br/><b className="text-3xl">{Number(value).toLocaleString()}</b></div>)}</div><div className="grid gap-4 lg:grid-cols-2"><section className="card"><h2 className="font-bold">Apps</h2>{apps.map(x=><p className="border-t py-2" key={x.name}>{x.name}: {x.ideas} ideas / {x.published} published</p>)}</section><section className="card"><h2 className="font-bold">Teams</h2>{teams.map(x=><p className="border-t py-2" key={x.team}>{x.team}: {x.ideas} ideas / {x.approved} approved / {x.overdue} overdue</p>)}</section></div><section className="card"><h2 className="font-bold">Recent Ideas</h2>{recent.map(x=><a className="block border-t py-2" href={`/ideas/${x.id}`} key={x.id}>{x.title} / {x.app_name} / {x.status}</a>)}</section></div>;
}
